

services:

  blackbox-exporter:
    image: prom/blackbox-exporter
    ports:
      - "9116:9115"
    volumes:
      - ./blackbox.yml:/etc/blackbox_exporter/config.yml

  python_exporter:
    build: ./python_exporter/
    ports:
      - "5001:5000"
      - "8002:8000"
    volumes:
      - ./python_exporter/endpoints.yml:/app/endpoints.yml  # Para que o arquivo de endpoints possa ser atualizado dinamicamente

  prometheus:
    image: prom/prometheus:v3.0.1
    ports:
      - "9091:9090"
    volumes:
      - ./etc/prometheus:/workspace
      - prometheus_data:/prometheus  # Persistência dos dados do Prometheus
    command:
      - '--config.file=/workspace/prometheus.yml'

  alertmanager:
    image: prom/alertmanager
    ports:
      - '9094:9093'
    volumes:
      - ./etc/alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml  # Persistência da configuração
      - alertmanager_data:/data  # Persistência dos dados do Alertmanager
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'

  grafana:
    image: grafana/grafana-oss:11.4.0
    ports:
      - "3001:3000"
    volumes:
      - ./etc/grafana/:/etc/grafana/provisioning/datasources  # Persistência dos datasources
      - ./etc/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml  # Configuração de provisionamento de dashboards
      - ./etc/dashboards:/etc/grafana/dashboards  # Diretório com os dashboards em JSON
      - grafana_data:/var/lib/grafana  # Persistência dos dados do Grafana (incluindo dashboards)
    depends_on:
      - prometheus

  alert-messenger:
    image: douglasvreis80/alert-messenger:1.1
    container_name: alert-messenger
    ports:
      - "8001:8001"
    environment:
      - GROUP_ID=120363335994170781@g.us
    working_dir: /wwebjs-bot
    command: npm start
    restart: unless-stopped

volumes:
  prometheus_data:
  alertmanager_data:
  grafana_data:
