version: '3.8'

services:

  blackbox-exporter:
    image: prom/blackbox-exporter
    ports:
      - "9115:9115"
    volumes:
      - ./blackbox.yml:/etc/blackbox_exporter/config.yml

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./etc/prometheus:/workspace
      - prometheus_data:/prometheus  # Persistência dos dados do Prometheus
    command:
      - '--config.file=/workspace/prometheus.yml'

  alertmanager:
    image: prom/alertmanager
    ports:
      - '9093:9093'
    volumes:
      - ./etc/alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml  # Persistência da configuração
      - alertmanager_data:/data  # Persistência dos dados do Alertmanager
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./etc/grafana/:/etc/grafana/provisioning/datasources  # Persistência dos datasources
      - ./etc/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml  # Configuração de provisionamento de dashboards
      - ./etc/dashboards:/etc/grafana/dashboards  # Diretório com os dashboards em JSON
      - grafana_data:/var/lib/grafana  # Persistência dos dados do Grafana (incluindo dashboards)
    depends_on:
      - prometheus
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
      GF_AUTH_DISABLE_LOGIN_FORM: "true"

volumes:
  prometheus_data:
  alertmanager_data:
  grafana_data:
