groups:

- name: HTTP Probe Alerts
  rules:
    - alert: HTTPProbeFailure
      expr: probe_http_status_code != 200
      for: 5m  # O alerta só será disparado se a condição persistir por 5 minutos
      labels:
        severity: critical
      annotations:
        summary: "HTTP Probe Failure"
        description: "O probe HTTP {{ $labels.instance }} falhou com status {{ $value }}."
