global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 1m # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
    - "alert_rules.yml"
    - "bidtrader_alerts.yml"
    - "system_alerts.yml"
  # - "http_requests_alerts.yml"
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ["localhost:9090"]
     
  - job_name: 'python_exporter'
    static_configs:
      - targets: ['python_exporter:5000']

  - job_name: 'BidTrader'
    metrics_path: /BidTrader/metrics
    scheme: https
    static_configs:
      - targets: ['backend-duxcloud.minervafoods.com:2022']
    tls_config:
      # Indica se o Prometheus deve verificar o certificado do servidor
      insecure_skip_verify: true # Defina como false em produção caso tenha os certificados corretos

  - job_name: 'backend.pcpfrigorifico.api'
    metrics_path: /metrics
    scheme: https
    static_configs:
      - targets: ['backend-duxcloud.minervafoods.com:1893']
    tls_config:
      # Indica se o Prometheus deve verificar o certificado do servidor
      insecure_skip_verify: true # Defina como false em produção caso tenha os certificados corretos

  - job_name: 'wminbageapp01.authlibrary.api'
    metrics_path: /metrics
    scheme: https
    static_configs:
      - targets: ['wminageapp01:9051']
    tls_config:
      # Indica se o Prometheus deve verificar o certificado do servidor
      insecure_skip_verify: true # Defina como false em produção caso tenha os certificados corretos


  - job_name: 'blackbox-apis-duxcloud'
    metrics_path: /probe
    params:
      module: [http_2xx_authenticated]  # Usando o módulo com autenticação
    static_configs:
      - targets:
          - https://int-backend-duxcloud.minervafoods.com:1722/Health
          - https://int-backend-duxcloud.minervafoods.com:1741/Health
          - https://int-backend-duxcloud.minervafoods.com:1861/Health
          - https://int-backend-duxcloud.minervafoods.com:1846/Health
          - https://int-backend-duxcloud.minervafoods.com:1840/Health
          - https://int-backend-duxcloud.minervafoods.com:1841/Health
          - https://int-backend-duxcloud.minervafoods.com:1842/Health
          - https://int-backend-duxcloud.minervafoods.com:1843/Health
          - https://int-backend-duxcloud.minervafoods.com:1844/Health
          - https://int-backend-duxcloud.minervafoods.com:3851/Health
          - https://int-backend-duxcloud.minervafoods.com:2022/swagger/
          - https://backend-duxcloud.minervafoods.com:2022/BidTrader/health
          
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - target_label: __address__
        replacement: blackbox-exporter:9115  # Endereço do Blackbox Exporter
      - source_labels: [__param_target]
        target_label: instance
      # Adicionando rótulos amigáveis como service_name
      - source_labels: [__param_target]
        regex: https://int-backend-duxcloud\.minervafoods\.com:1722/Health
        target_label: service_name
        replacement: PessoaAPI
      - source_labels: [__param_target]
        regex: https://int-backend-duxcloud\.minervafoods\.com:1741/Health
        target_label: service_name
        replacement: SuprimentosAPI
      - source_labels: [__param_target]
        regex: https://int-backend-duxcloud\.minervafoods\.com:1861/Health
        target_label: service_name
        replacement: RoadnetAPI
      - source_labels: [__param_target]
        regex: https://int-backend-duxcloud\.minervafoods\.com:1846/Health
        target_label: service_name
        replacement: SupFriAPI
      - source_labels: [__param_target]
        regex: https://int-backend-duxcloud\.minervafoods\.com:1840/Health
        target_label: service_name
        replacement: DataSourceAPI
      - source_labels: [__param_target]
        regex: https://int-backend-duxcloud\.minervafoods\.com:1841/Health
        target_label: service_name
        replacement: ExchangeAPI
      - source_labels: [__param_target]
        regex: https://int-backend-duxcloud\.minervafoods\.com:1842/Health
        target_label: service_name
        replacement: ReceiverAPI
      - source_labels: [__param_target]
        regex: https://int-backend-duxcloud\.minervafoods\.com:1843/Health
        target_label: service_name
        replacement: IntegrationAPI
      - source_labels: [__param_target]
        regex: https://int-backend-duxcloud\.minervafoods\.com:1844/Health
        target_label: service_name
        replacement: InvoiceEventAPI
      - source_labels: [__param_target]
        regex: https://int-backend-duxcloud\.minervafoods\.com:3851/Health
        target_label: service_name
        replacement: IntegrationControlAPI.Replica1
      - source_labels: [__param_target]
        regex: https://int-backend-duxcloud\.minervafoods\.com:2022/swagger/
        target_label: service_name
        replacement: OcelotGateway
      - source_labels: [__param_target]
        regex: https://backend-duxcloud\.minervafoods\.com:2022/BidTrader/health
        target_label: service_name
        replacement: BidTrader

  - job_name: 'blackbox-multiembarcador'
    metrics_path: /probe
    params:
      module: [http_2xx_authenticated]  # Usando o módulo com autenticação
    static_configs:
      - targets:
        - https://minervafoods.multiembarcador.com.br/SGT.WebService/Cargas.svc
        - https://minervafoods.multiembarcador.com.br/SGT.WebService/CTe.svc
        - https://minervafoods.multiembarcador.com.br/SGT.WebService/NFS.svc
        - https://minervafoods.multiembarcador.com.br/SGT.WebService/NFe.svc
        - https://minervafoods.multiembarcador.com.br/SGT.WebService/MDFe.svc
        - https://minervafoods.multiembarcador.com.br/SGT.WebService/Ocorrencias.svc
        - https://minervafoods.multiembarcador.com.br/SGT.WebService/JanelaCarregamento.svc
        - https://minervafoods.multiembarcador.com.br/SGT.WebService/Empresa.svc
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - target_label: __address__
        replacement: blackbox-exporter:9115  # Endereço do Blackbox Exporter
      - source_labels: [__param_target]
        target_label: instance

      # Adicionando rótulos amigáveis como service_name
      - source_labels: [__param_target]
        regex: https://minervafoods\.multiembarcador\.com\.br/SGT\.WebService/Cargas\.svc
        target_label: service_name
        replacement: Multiembarcador - Cargas
      - source_labels: [__param_target]
        regex: https://minervafoods\.multiembarcador\.com\.br/SGT\.WebService/CTe\.svc
        target_label: service_name
        replacement: Multiembarcador - CTe
      - source_labels: [__param_target]
        regex: https://minervafoods\.multiembarcador\.com\.br/SGT\.WebService/NFS\.svc
        target_label: service_name
        replacement: Multiembarcador - NFS
      - source_labels: [__param_target]
        regex: https://minervafoods\.multiembarcador\.com\.br/SGT\.WebService/NFe\.svc
        target_label: service_name
        replacement: Multiembarcador - NFe
      - source_labels: [__param_target]
        regex: https://minervafoods\.multiembarcador\.com\.br/SGT\.WebService/MDFe\.svc
        target_label: service_name
        replacement: Multiembarcador - MDFe
      - source_labels: [__param_target]
        regex: https://minervafoods\.multiembarcador\.com\.br/SGT\.WebService/Ocorrencias\.svc
        target_label: service_name
        replacement: Multiembarcador - Ocorrências
      - source_labels: [__param_target]
        regex: https://minervafoods\.multiembarcador\.com\.br/SGT\.WebService/JanelaCarregamento\.svc
        target_label: service_name
        replacement: Multiembarcador - Janela de Carregamento
      - source_labels: [__param_target]
        regex: https://minervafoods\.multiembarcador\.com\.br/SGT\.WebService/Empresa\.svc
        target_label: service_name
        replacement: Multiembarcador - Empresa


  - job_name: 'blackbox-api-apppecuarista'
    metrics_path: /probe
    params:
      module: [http_2xx_authenticated]  # Usando o módulo com autenticação
    static_configs:
      - targets:
        - https://pecuarista.minervafoods.com:8095/api/
        - https://pecuarista.minervafoods.com:8096/
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - target_label: __address__
        replacement: blackbox-exporter:9115  # Endereço do Blackbox Exporter
      - source_labels: [__param_target]
        target_label: instance

      - source_labels: [__param_target]
        regex: https://pecuarista\.minervafoods\.com:8095/api/
        target_label: service_name
        replacement: API - App Pecuarista - Porta 8095
      - source_labels: [__param_target]
        regex: https://pecuarista\.minervafoods\.com:8096/
        target_label: service_name
        replacement: CMS - App Pecuarista - Porta 8096