global:
  # Configurações globais podem ser omitidas se não forem usadas.
  # Se for necessário configurar autenticação de e-mail ou outras opções, adicione-as aqui.

route:
  # Define a rota padrão para os alertas.
  receiver: 'combined-receivers'

receivers:
  - name: 'combined-receivers'
    webhook_configs:     
      - url: 'http://alert-messenger:8001/webhook'
        send_resolved: true
